# Generated by Django 4.2.5 on 2023-09-17 13:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название роута')),
                ('owner', models.CharField(max_length=128, verbose_name='Владелец')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='MLAlgorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название алгоритма')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
                ('code', models.CharField(max_length=50000, verbose_name='Код')),
                ('version', models.CharField(max_length=128, verbose_name='Версия')),
                ('owner', models.CharField(max_length=128, verbose_name='Владелец')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('parent_endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endpoints.endpoint', verbose_name='Роут')),
            ],
        ),
        migrations.CreateModel(
            name='MLRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.CharField(max_length=10000, verbose_name='Данные')),
                ('full_response', models.CharField(max_length=10000, verbose_name='Ответ')),
                ('response', models.CharField(max_length=10000, verbose_name='Ответ-JSON')),
                ('feedback', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Обратная связь')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата запроса')),
                ('parent_mlalgorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endpoints.mlalgorithm', verbose_name='Алгоритм')),
            ],
        ),
        migrations.CreateModel(
            name='MLAlgorithmStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=128, verbose_name='Статус алгоритма')),
                ('active', models.BooleanField(verbose_name='Активный')),
                ('created_by', models.CharField(max_length=128, verbose_name='Создан')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('parent_mlalgorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='endpoints.mlalgorithm', verbose_name='Алгоритм')),
            ],
        ),
    ]
