# Generated by Django 4.2.5 on 2023-09-19 22:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endpoint',
            options={'verbose_name': 'Роут', 'verbose_name_plural': 'Роуты'},
        ),
        migrations.AlterModelOptions(
            name='mlalgorithm',
            options={'verbose_name': 'Алгоритм', 'verbose_name_plural': 'Алгоритмы'},
        ),
        migrations.AlterModelOptions(
            name='mlalgorithmstatus',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterModelOptions(
            name='mlrequest',
            options={'verbose_name': 'Запрос', 'verbose_name_plural': 'Запросы'},
        ),
        migrations.CreateModel(
            name='ABTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000, verbose_name='Название теста')),
                ('created_by', models.CharField(max_length=128, verbose_name='Создан')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата начала')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('summary', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Краткое содержание')),
                ('parent_mlalgorithm_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_mlalgorithm_1', to='endpoints.mlalgorithm')),
                ('parent_mlalgorithm_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_mlalgorithm_2', to='endpoints.mlalgorithm')),
            ],
            options={
                'verbose_name': 'АБ-тест',
                'verbose_name_plural': 'АБ-тесты',
            },
        ),
    ]
